import type { Metadata } from "next";
import "./globals.css";
import { Plus_Jakarta_Sans } from 'next/font/google';
import TabBar from './components/TabBar';
import PageTransition from './components/PageTransition';

const plusJakarta = Plus_Jakarta_Sans({ 
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-plus-jakarta',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={plusJakarta.variable}>
      <body className="bg-white dark:bg-neutral-900 font-sans text-neutral-900 dark:text-neutral-50">
        <PageTransition>
          {children}
        </PageTransition>
        <TabBar />
      </body>
    </html>
  );
}
